---
title: "Chapter 2"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Chapter 2: Training Machine Learning Algorithms for Classification

## McCullock-Pitts (MCP) neuron.

* Initialize the weights to 0 or small random number.
* For each training sample x(i), perform the following steps 1) Compute output value y_hat (class label), 2) update the weights in the weight vector.

* `w_j := w_j + delta_w_j`
* `delta_w_j = eta( y(i) - y_hat(i))*x_j(i)`

`eta: learning rate` (0-1)
`y(i): true class`
`y_hat(i): *predicted* true class`

```{python}

# Learning rule examples of delta_w_j

y_i = 1
y_hat_i = 1
#eta*(y_i-y_hat_i)*x_j_i
#=> eta*(0i)*x_j_i

y_i = 1
y_hat_i = -1
#eta*(y_i-y_hat_i)*x_j_i
#=> eta*(1--1)*x_j_i

y_i = -1
y_hat_i = 1
#eta*(y_i-y_hat_i)*x_j_i
#=> eta*(-1-1)*x_j_i

```

### Implementation

```{python}

import numpy as np

class Perceptron(object):
    def __init__(self,eta=0.01,n_iter=10):
        self.eta = eta
        self.n_iter = n_iter
    def fit(self,X,y):
        self.w_ = np.zeros(1+X.shape[1])
        self.errors_ = []
        for _ in range(self.n_iter):
          print("Iteration: " + str(_))
          errors = 0
          for xi, target in zip(X,y):
            update = self.eta * (target - self.predict(xi))
            self.w_[1:] += update * xi
            self.w_[0] += update
            errors += int(update != 0.0)
          print("Updating..")
          print(update)
          self.errors_.append(errors)
          print("Resulting errors:")
          print(self.errors_)
          print("Resulting weights:")
          print(self.w_)
          print("\n")
        return self
    def net_input(self,X):
      return np.dot(X,self.w_[1:]) + self.w_[0]
    def predict(self,X):
      return np.where(self.net_input(X) >= 0.0, 1, -1)

```

### Iris dataset

Show first 5 rows.

```{python}

import pandas as pd
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',header=None)
df.tail()

```

Plot the labels and two of the dimensions.

```{python}

import matplotlib.pyplot as plt
import numpy as np

y = df.iloc[0:100,4].values
y = np.where(y == 'Iris-setosa',-1,1)
X = df.iloc[0:100, [0, 2]].values
plt.clf()
plt.scatter(X[:50,0], X[:50, 1], color='red', marker='o', label='setosa')
plt.scatter(X[50:100,0], X[50:100, 1], color='blue', marker='x', label='versicolor')
plt.xlabel('sepal length')
plt.ylabel('petal length')
plt.legend(loc='upper left')
plt.show()

```

Perceptron classifier

```{python}

plt.clf()

ppn = Perceptron(eta = 0.1, n_iter = 10)
ppn.fit(X, y)

plt.plot(range(1, len(ppn.errors_) + 1), ppn.errors_, marker='o')
plt.xlabel('Epochs')
plt.ylabel('Number of misclassifications')
plt.show()

```

Perceptron boundaries

```{python}

from matplotlib.colors import ListedColormap

def plot_decision_regions(X, y, classifier, resolution=0.02):
    markers = ('s','x','o','^','v')
    colors = ('red','blue','lightgreen','gray','cyan')
    cmap = ListedColormap(colors[:len(np.unique(y))])
    # plot surfaces
    x1_min, x1_max = X[:,0].min() - 1, X[:, 0].max() + 1
    x2_min, x2_max = X[:,1].min() - 1, X[:, 1].max() + 1
    xx1, xx2 = np.meshgrid(np.arange(x1_min, x1_max, resolution), np.arange(x2_min,x2_max,resolution))
    Z = classifier.predict(np.array([xx1.ravel(), xx2.ravel()]).T)
    Z = Z.reshape(xx1.shape)
    plt.clf()
    plt.contourf(xx1, xx2, Z, alpha = 0.4, cmap=cmap)
    plt.xlim(xx1.min(), xx1.max())
    plt.ylim(xx2.min(), xx2.max())
    # class samples
    for idx, cl in enumerate(np.unique(y)):
      plt.scatter(x=X[y == cl,0], y=X[y == cl, 1], alpha=0.8, c=cmap(idx), marker=markers[idx], label=cl)

plot_decision_regions(X, y, classifier=ppn)
plt.xlabel('sepal length (cm)')
plt.ylabel('petal length (cm)')
plt.legend(loc='upper left')
plt.show()

```


## Adaline: ADAptive LInear NEuron

A `linear activation function` is used for learning the weights.
A `quantizer` is used to predict class labels.

### Cost function

An objective function that we want to minimize, typically through `gradient descent`.

In Adaline this will be the cost function J to learn the `Sum of Squared Errors (SSE)`

`J(w) = 1/2*sum_i(y_i-phi(zeta_i))^2`.

### Implementation

```{python}

class AdalineGD(object):
  def __init__(self,eta=0.01,n_iter=50):
    self.eta = eta
    self.n_iter = n_iter
  def fit(self, X, y):
    self.w_ = np.zeros(1 + X.shape[1])
    print("Initial weights:")
    print(self.w_)
    self.cost_ = []
    for i in range(self.n_iter):
      output = self.net_input(X)
      errors = (y - output)
      self.w_[1:] += self.eta * X.T.dot(errors)
      self.w_[0] += self.eta * errors.sum()
      cost = (errors**2).sum() / 2.0
      if (i%1000==0):
        print("Iteration: " + str(i))
        print("Updated weights: ")
        print(self.w_)
        print("Cost: " + str(cost))
      self.cost_.append(cost)
    return self
  def net_input(self, X):
    return np.dot(X,self.w_[1:]) + self.w_[0]
  def activation(self, X):
    return self.net_input(X)
  def predict(self, X):
    return np.where(self.activation(X) >= 0.0, 1, -1)
  

```

### Plot error

```{python}

plt.clf()
ada1 = AdalineGD(n_iter=50000,eta=0.00001).fit(X,y)
plt.plot(range(1,len(ada1.cost_)+1),np.log10(ada1.cost_),marker='o')
plt.show()

```

### Plot Adaline boundaries

```{python}
plot_decision_regions(X, y, classifier=ada1)
plt.xlabel('sepal length (cm)')
plt.ylabel('petal length (cm)')
plt.legend(loc='upper left')
plt.show()
```

### Standardize

```{python}

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',header=None,encoding='utf-8')
df.tail()

y = df.iloc[0:100, 4].values
y = np.where(y == 'Iris-setosa', -1, 1)
X = df.iloc[0:100, [0, 2]].values
plt.scatter(X[:50, 0], X[:50, 1],color='red', marker='o', label='setosa')
plt.scatter(X[50:100, 0], X[50:100, 1],color='blue', marker='x', label='versicolor')
plt.xlabel('sepal length [cm]')
plt.ylabel('petal length [cm]')
plt.legend(loc='upper left')
plt.show()

X_std = np.copy(X)
X_std[:,0] = (X[:,0] - X[:,0].mean()) / X[:,0].std()
X_std[:,1] = (X[:,1] - X[:,1].mean()) / X[:,1].std()

ada_gd = AdalineGD(n_iter=15, eta=0.01)
ada_gd.fit(X_std, y)

plt.clf()
plot_decision_regions(X_std, y, classifier=ada_gd)
plt.title('Adaline - Gradient Descent')
plt.xlabel('sepal length [standardized]')
plt.ylabel('petal length [standardized]')
plt.legend(loc='upper left')
plt.tight_layout()
plt.show()

plt.clf()
plt.plot(range(1, len(ada_gd.cost_) + 1),ada_gd.cost_, marker='o')
plt.xlabel('Epochs')
plt.ylabel('Sum-squared-error')
plt.tight_layout()
plt.show()


```


## Stochastic gradient descent

Large datasets, a preferred method is to use incremental weights for each training sample. Enables `iterative/on-line learning`.

```{python}

class AdalineSGD(object):

    def __init__(self, eta=0.01, n_iter=10,
              shuffle=True, random_state=None):
        self.eta = eta
        self.n_iter = n_iter
        self.w_initialized = False
        self.shuffle = shuffle
        self.random_state = random_state
    
    def fit(self, X, y):

        self._initialize_weights(X.shape[1])
        self.cost_ = []
        print("Initial weights: ")
        print(self.w_)
        for i in range(self.n_iter):
            if self.shuffle:
                X, y = self._shuffle(X, y)
            cost = []
            for xi, target in zip(X, y):
                cost.append(self._update_weights(xi, target))
            avg_cost = sum(cost) / len(y)
            self.cost_.append(avg_cost)
            if (i % 10 == 0):
              print("Iteration: " + str(i))
              print("- Weights:")
              print(self.w_)
              print("- Total cost: " + str(sum(cost)))
              print("- Length: " + str(len(y)))
              print("- Avg cost: " + str(avg_cost))
              
        return self
    
    def partial_fit(self, X, y):
        if not self.w_initialized:
            self._initialize_weights(X.shape[1])
        if y.ravel().shape[0] > 1:
            for xi, target in zip(X, y):
                self._update_weights(xi, target)
        else:
            self._update_weights(X, y)
        return self
    
    def _shuffle(self, X, y):
        r = self.rgen.permutation(len(y))
        return X[r], y[r]
    
    def _initialize_weights(self, m):
        self.rgen = np.random.RandomState(self.random_state)
        self.w_ = self.rgen.normal(loc=0.0, scale=0.01,
                                   size=1 + m)
        self.w_initialized = True
    
    def _update_weights(self, xi, target):
        output = self.activation(self.net_input(xi))
        error = (target - output)
        self.w_[1:] += self.eta * xi.dot(error)
        self.w_[0] += self.eta * error
        cost = 0.5 * error**2
        return cost
    
    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]
    
    def activation(self, X):
        return X
    
    def predict(self, X):
        return np.where(self.activation(self.net_input(X))
                        >= 0.0, 1, -1)

```

```{python}

ada_sgd = AdalineSGD(n_iter=150, eta=0.01, random_state=1)
ada_sgd.fit(X_std, y)

plt.clf()
plt.plot(range(1, len(ada_sgd.cost_) + 1), ada_sgd.cost_,marker='o')
plt.xlabel('Epochs')
plt.ylabel('Average Cost')
plt.tight_layout()
plt.show()



```

